### ISSUE TITLE
Besprechungstreffen eures Projekts

### ISSUE THREAD

**Issue by MrEbbinghaus** [ProPra16/programmierpraktikum-abschlussprojekt-null#15]
Hallo,

Bitte sprecht mit mir einen Termin ab, wo ihr mir euer Projekt vorstellt, in eurem derzeitigen Zustand.
Von Problemen und Lösungen berichtet oder zu bestehenden Themen fragen stellt.

Der Termin sollte höchstens 30min lang sein. Es geht nur darum, zu sehen was ihr wie macht.

Gruß,

Björn

**Comment by Patrick-Remy** [comment]
Haben dir eine E-Mail geschrieben.
