### ISSUE TITLE
Remove old "Out of time" dialogs

### ISSUE THREAD

**Issue by MrEbbinghaus** [ProPra16/programmierpraktikum-abschlussprojekt-null#71]
Multiple "Out of time" dialogs are stacking, if not closed.

![](https://photos-6.dropbox.com/t/2/AAA75JeqrDb4-Y62s0LxCSnofL7AwlFGITluuSHj_LsLUg/12/23654713/png/32x32/1/_/1/2/Screenshot%202016-07-17%2022.47.30.png/EL7d5REYmNsFIAcoBw/hZs53UIDds55arSVOiP_a0NpBlOVZQr5rJStvuxTx-0?dl=0&size=2048x1536&size_mode=3)

**Comment by MrEbbinghaus** [comment]
Is it solved? 

(Tip: you can close issues by commit messages. E.g.;git commit -m "blabla fixes #71")

**Comment by pafis** [comment]
Yup, should be fixed. Unfortunately, it didn't sync right away. Had a connection error. But should be up now :D

**Comment by Patrick-Remy** [comment]
I recently refactored the solving code, and let the thread really stop and restart

**Comment by pafis** [comment]
Your build failed....good work though :D

**Comment by Patrick-Remy** [comment]
Docker issue - not my fault ;-)
