### ISSUE TITLE
Vorstellen des Projekts

### ISSUE THREAD

**Issue by bendisposto** [ProPra16/programmierpraktikum-abschlussprojekt-null#73]
ich würde euch bitten, euere Projekt in der Vorlesung am Donnerstag kurz (max. 10 min) vorzustellen.

**Comment by pafis** [comment]
Ok, werden wir machen! :) Die Gruppe trifft sich dann morgen nochmal, um eine kleine Präsentation auszuarbeiten.

**Comment by bendisposto** [comment]
Ich habe einen blaues Ringbuch auf dem Tisch im HS gefunden, gehört das einem von euch?

**Comment by pafis** [comment]
Das ist leider nicht unser Ringbuch :/
